In [1]:
import numpy as np

X = np.array([[1,1,0,0],
              [1,1,0,1],
              [0,0,1,1],
              [0,0,1,0]])

C = []              # Cluster list
T = 0.6             # Threshold
C.append(X[0])      # First pattern becomes first cluster

cluster_map = []    # Store cluster index for each pattern

for i in range(len(X)):
    print("***************************")
    print("Input =", X[i])

    found = 0
    for j in range(len(C)):
        print("\nCluster", j, "=", C[j])
        AND = X[i] & C[j]
        print("AND =", AND)

        match = AND.sum() / X[i].sum()
        print("Match =", match)

        if match > T:
            C[j] = AND
            found = 1
            cluster_map.append(j)
            print("→ Belongs to existing cluster", cluster_map)
            break

    if found == 0:
        C.append(X[i])
        cluster_map.append(len(C)-1)
        print("→ New cluster created", cluster_map)

print("*****************************")
print("Final Clusters:")
for idx, cl in enumerate(C):
    print("Cluster", idx, "=", cl)

print("\nPattern → Cluster Mapping:")
for i in range(len(X)):
    print(X[i], "→ Cluster", cluster_map[i])

***************************
Input = [1 1 0 0]

Cluster 0 = [1 1 0 0]
AND = [1 1 0 0]
Match = 1.0
→ Belongs to existing cluster [0]
***************************
Input = [1 1 0 1]

Cluster 0 = [1 1 0 0]
AND = [1 1 0 0]
Match = 0.6666666666666666
→ Belongs to existing cluster [0, 0]
***************************
Input = [0 0 1 1]

Cluster 0 = [1 1 0 0]
AND = [0 0 0 0]
Match = 0.0
→ New cluster created [0, 0, 1]
***************************
Input = [0 0 1 0]

Cluster 0 = [1 1 0 0]
AND = [0 0 0 0]
Match = 0.0

Cluster 1 = [0 0 1 1]
AND = [0 0 1 0]
Match = 1.0
→ Belongs to existing cluster [0, 0, 1, 1]
*****************************
Final Clusters:
Cluster 0 = [1 1 0 0]
Cluster 1 = [0 0 1 0]

Pattern → Cluster Mapping:
[1 1 0 0] → Cluster 0
[1 1 0 1] → Cluster 0
[0 0 1 1] → Cluster 1
[0 0 1 0] → Cluster 1
