In [62]:
import numpy as np
x = []
w=np.zeros(7)

for i in range(10):
    asc=ord(str(i))
    bin=format(asc,'07b')
    binary = [int(bit) for bit in bin]
    x.append(binary)
     
x=np.array(x)
print(x)

print("----For t------")

t = []
for i in range(10):
    if i %2 ==0:
        t.append(1)
    else:
        t.append(0)
    
print(t)  

w = np.zeros(7)
b = 0
Alpha = 0

for epoch in range(50):
    for j in range (10):
        initial_output = t[j]
        net = np.dot(x[j], w) + b
        if net >= 0:
            yin = 1
        else:
            yin = 0   
        #yin = 1 if net >= 0 else 0
        error = t[j] - yin
        w += Alpha * error * x[j]
        b += Alpha * error
        print("Inputs",j,"Output",initial_output,"T.R",net)
    # print("initial_output",initial_output)


[[0 1 1 0 0 0 0]
 [0 1 1 0 0 0 1]
 [0 1 1 0 0 1 0]
 [0 1 1 0 0 1 1]
 [0 1 1 0 1 0 0]
 [0 1 1 0 1 0 1]
 [0 1 1 0 1 1 0]
 [0 1 1 0 1 1 1]
 [0 1 1 1 0 0 0]
 [0 1 1 1 0 0 1]]
----For t------
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
Inputs 0 Output 1 T.R 0.0
Inputs 1 Output 0 T.R 0.0
Inputs 2 Output 1 T.R 0.0
Inputs 3 Output 0 T.R 0.0
Inputs 4 Output 1 T.R 0.0
Inputs 5 Output 0 T.R 0.0
Inputs 6 Output 1 T.R 0.0
Inputs 7 Output 0 T.R 0.0
Inputs 8 Output 1 T.R 0.0
Inputs 9 Output 0 T.R 0.0
Inputs 0 Output 1 T.R 0.0
Inputs 1 Output 0 T.R 0.0
Inputs 2 Output 1 T.R 0.0
Inputs 3 Output 0 T.R 0.0
Inputs 4 Output 1 T.R 0.0
Inputs 5 Output 0 T.R 0.0
Inputs 6 Output 1 T.R 0.0
Inputs 7 Output 0 T.R 0.0
Inputs 8 Output 1 T.R 0.0
Inputs 9 Output 0 T.R 0.0
Inputs 0 Output 1 T.R 0.0
Inputs 1 Output 0 T.R 0.0
Inputs 2 Output 1 T.R 0.0
Inputs 3 Output 0 T.R 0.0
Inputs 4 Output 1 T.R 0.0
Inputs 5 Output 0 T.R 0.0
Inputs 6 Output 1 T.R 0.0
Inputs 7 Output 0 T.R 0.0
Inputs 8 Output 1 T.R 0.0
Inputs 9 Output 0 T.R 0.0
In